// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWsJvlHEWpwlg_DTJI5yrZHkJHt3LcUl0',
    appId: '1:804162267714:web:8e5aa99270325934f19bdb',
    messagingSenderId: '804162267714',
    projectId: 'cyber-shield-801d3',
    authDomain: 'cyber-shield-801d3.firebaseapp.com',
    storageBucket: 'cyber-shield-801d3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWfnqyzZx9R4-vnfiWtb7ju9l2Zd-iw0',
    appId: '1:804162267714:ios:a92c13c771ce414cf19bdb',
    messagingSenderId: '804162267714',
    projectId: 'cyber-shield-801d3',
    storageBucket: 'cyber-shield-801d3.firebasestorage.app',
    iosBundleId: 'com.example.cyberShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYWfnqyzZx9R4-vnfiWtb7ju9l2Zd-iw0',
    appId: '1:804162267714:ios:a92c13c771ce414cf19bdb',
    messagingSenderId: '804162267714',
    projectId: 'cyber-shield-801d3',
    storageBucket: 'cyber-shield-801d3.firebasestorage.app',
    iosBundleId: 'com.example.cyberShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWsJvlHEWpwlg_DTJI5yrZHkJHt3LcUl0',
    appId: '1:804162267714:web:3c3ea24068bd73cbf19bdb',
    messagingSenderId: '804162267714',
    projectId: 'cyber-shield-801d3',
    authDomain: 'cyber-shield-801d3.firebaseapp.com',
    storageBucket: 'cyber-shield-801d3.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQZ58rkYYM-l-gU9oMMm79gAnxAByGWiQ',
    appId: '1:804162267714:android:02d084a7ad14b9fdf19bdb',
    messagingSenderId: '804162267714',
    projectId: 'cyber-shield-801d3',
    storageBucket: 'cyber-shield-801d3.firebasestorage.app',
  );
}
